### PR TITLE
tweaks nav menu/positioning

### PR DESCRIPTION
**Pull request by rediris**
See
* https://github.com/gymnasium/tracker/issues/126
* https://github.com/gymnasium/tracker/issues/134

I decided to abandon the "going down the rabbithole" branch I had started previously. This accomplishes the end result with significantly less catastrophic damage to the rest of the theme.

Also addressed by this are the inconsistent left/right spacing of the nav at various breakpoints.

### CODE REVIEW

**Review by andrewpmiller — APPROVED** [review]
This looks good to me! @jgagne ?

image

**Review by jgagne — CHANGES_REQUESTED** [review]
@rediris

Thoughts on adjusting the nav menu by setting `height: 50px` to `height: auto` on lines [432](https://github.com/gymnasium/openedx-theme/blob/161939866eb2079b20f1d02ce5babb19c150cc82/lms/static/sass/_gymnasium.scss#L432) and [446](https://github.com/gymnasium/openedx-theme/blob/161939866eb2079b20f1d02ce5babb19c150cc82/lms/static/sass/_gymnasium.scss#L446) in lieu of updating the stacking context/order.

SCSS: 

https://github.com/gymnasium/openedx-theme/blob/161939866eb2079b20f1d02ce5babb19c150cc82/lms/static/sass/_gymnasium.scss#L431-L449

Result:

navbar-height-adjust

**Comment by rediris** [comment]
@jgagne sure, that works for me, if we don't want that overlapping button effect. I'll go ahead and make the change.

**Comment by jgagne** [comment]
@rediris — Cool, thanks for digging into the weeds on this.

**Review by jgagne — APPROVED** [review]

**Comment by jgagne** [comment]
@rediris — Safe to delete the branch?

**Comment by rediris** [comment]
@jgagne done!

**Pull request merged**
